name: CI

on:
  workflow_dispatch:
  push:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3 # Use up to 3 cpus to build juceaide, etc

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  BuildAndTest:

    name: ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c   # pin@v3
        with:
          fetch-depth: 1

      - name: Build and test
        run: python3 scripts/RunTests.py
